// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #TaskInput is the typed input for a `task:` verb step composed into
// a candy/box/task plan (`- run: ... \n  task: {task: build}`), so a plan can
// invoke another declared task.
type TaskInput struct {
	// task is the declared task entity name to run.
	Task string `json:"task"`

	// dir optionally overrides the task's working directory for this invocation.
	Dir string `json:"dir,omitempty"`

	// params are NAME=VALUE overrides for the task's declared params.
	Param []string `json:"param,omitempty"`
}
